<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>warehouse_gazebo</name>
  <version>0.0.0</version>
  <description>Gazebo simulation for warehouse robot with conveyor and ArUco products</description>
  <maintainer email="omm@todo.todo">omm</maintainer>
  <license>TODO: License</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gazebo_dev</depend>
  <depend>gazebo_ros</depend>
  <depend>gazebo_ros2_control</depend>
  <depend>gazebo_msgs</depend>
  <depend>controller_manager</depend>
  <depend>robot_state_publisher</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>xacro</depend>
  <depend>ament_index_python</depend>
  <depend>python3-yaml</depend>
  <depend>warehouse_robot_description</depend>
  <depend>warehouse_moveit_config</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
