<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>warehouse_bringup</name>
  <version>0.0.0</version>
  <description>Top-level launch orchestration for the GP12 digital twin</description>
  <maintainer email="chaitanya@todo.todo">chaitanya</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>warehouse_robot_description</exec_depend>
  <exec_depend>warehouse_moveit_config</exec_depend>
  <exec_depend>warehouse_gazebo</exec_depend>
  <exec_depend>warehouse_perception</exec_depend>
  <exec_depend>warehouse_pick_place</exec_depend>
  <exec_depend>warehouse_controller</exec_depend>
  <exec_depend>warehouse_aruco_detection</exec_depend>
  <exec_depend>diagnostic_aggregator</exec_depend>
  <exec_depend>rqt_robot_monitor</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
